In [ ]:
#Cleaning Data
def clean_data(df,O_to_nun_columns):
  import pandas as pd
#Data conversion into "numerical" for columns containing numerical information
  for i in O_to_nun_columns :
    df[i] = round(pd.to_numeric(df[i],'coerce')) #'coerce' replace str data to NaN'

#suppression of '\N' data -> replacing by NaN
  NaN = float("NaN")
  for index,value in enumerate(df.columns):
    df[value] = df[value].replace(['\\N'],NaN)
  return(df)